# Generated by Django 6.0.5 on 2026-05-31 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tiket',
            field=models.ForeignKey(default=1, help_text='Pesanan tiket yang dibayar', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.tiket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('E_WALLET', 'E-Wallet'), ('BANK_TRANSFER', 'Bank Transfer')], default='E_WALLET', max_length=20),
        ),
    ]
