<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-31 02:33
=======
# Generated by Django 6.0.5 on 2026-05-31 05:28
>>>>>>> 1b3c2f5f44f87f5971a8a258276f44f0747bb7c3

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
