# Generated by Django 6.0.5 on 2026-05-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kursi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kursi', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('TERSEDIA', 'Tersedia'), ('DIPESAN', 'Dipesan')], default='TERSEDIA', max_length=20)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_booking', models.CharField(max_length=20)),
                ('nama_pemesan', models.CharField(max_length=100)),
                ('jenis_tiket', models.CharField(choices=[('reguler', 'Reguler'), ('pelajar', 'Pelajar'), ('weekend', 'Weekend')], max_length=20)),
                ('harga', models.IntegerField()),
                ('jumlah_kursi', models.IntegerField()),
                ('total_harga', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('BATAL', 'Batal')], default='AKTIF', max_length=20)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.jadwaltayang')),
                ('kursi', models.ManyToManyField(to='booking.kursi')),
            ],
        ),
    ]
