# Generated by Django 6.0.5 on 2026-05-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('judul', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('durasi', models.IntegerField()),
                ('sinopsis', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='poster/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor_studio', models.IntegerField()),
                ('kapasitas', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JadwalTayang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('tanggal', models.DateField()),
                ('jam', models.TimeField()),
                ('harga_dasar', models.PositiveIntegerField(default=35000)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.film')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.studio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
