# Generated by Django 6.0.5 on 2026-05-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='dibuat_pada',
        ),
        migrations.RemoveField(
            model_name='film',
            name='diubah_pada',
        ),
        migrations.RemoveField(
            model_name='jadwaltayang',
            name='dibuat_pada',
        ),
        migrations.RemoveField(
            model_name='jadwaltayang',
            name='diubah_pada',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='dibuat_pada',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='diubah_pada',
        ),
    ]
